### ISSUE TITLE
关于数据集制备

### ISSUE THREAD

**Issue by Linaom1214** [YimianDai/open-sirst-v2#1]
戴博士，您好：
非常感谢您的工作，本数据集中实拍的图像是怎么获得的呢？可以提供相关的设备的参数吗？我们实验室也想自己制作一个类似的数据集。再次感谢您的工作。

**Comment by YimianDai** [comment]
中波相机，镜头焦距26mm，F数1.04，分辨率1024×1024，像元大小15um×15um，波段3.7～4.8um，NETD=19.2mK。

长波相机，镜头焦距50mm，F数2，分辨率640×512（有的是512×512），像元大小25um×25um，波段7.7～9.3um，NETD=26.2mK。

抱歉回复迟了，之前一直在医院。
