### ISSUE TITLE
关于sirstv1和sirstv2

### ISSUE THREAD

**Issue by jzw0707** [YimianDai/open-sirst-v2#2]
戴博士您好，最近在搞关注您相关的工作，无论从数据集和工作创新都觉得非常棒，在学习的过程中我有一个小问题，想问下您
发布的sirst数据集的v1和v2之间有什么关系，如果做实验是否只需要用v2即可，万分感谢，期待您的回复！

**Comment by YimianDai** [comment]
您好！

v1 是第一次发布的数据集，分辨率比较低、数量也少，检测难度较低；
v2 是第二次发布的，增加了很多更加复杂的背景，目标也更加难检测一点，但是 v2 是 完全包含 v1 的。

我个人目前做实验是只做 v2 的，v1 一般用于初步验证想法。
