### ISSUE TITLE
关于数据集图片的波段

### ISSUE THREAD

**Issue by wangqivicky** [YimianDai/open-sirst-v2#3]
您好，background图片有很多不同的像素。请问是不是像素的某一边达到1000+值的是中波红外相机拍到的

**Comment by YimianDai** [comment]
画质比较好，分辨率 1K 的是中波的

**Comment by wangqivicky** [comment]
谢谢，请问其余小分辨率的都是长波红外的吗？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yimian Dai ***@***.***&gt;
发送时间: 2024年9月19日 18:02
收件人: YimianDai/open-sirst-v2 ***@***.***&gt;
抄送: wangqivicky ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [YimianDai/open-sirst-v2] 关于数据集图片的波段 (Issue #3)





 
画质比较好，分辨率 1K 的是中波的
